@extends('pub_theme::layouts.plane')
@section('body')
@include('pub_theme::layouts.partials.headernav')
{{--
@include('theme::modal_ajax')
--}}
@yield('content')
@include('pub_theme::layouts.partials.footer')
@endsection